# Generated by Django 4.1 on 2026-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scam',
            name='scam_type',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('sms', 'SMS Scam'), ('investment', 'Investment Scam')], max_length=100),
        ),
    ]
