# Generated by Django 5.2.13 on 2026-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scams', '0002_alter_scam_scam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scam',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone_call', 'Phone call'), ('social_media', 'Social media'), ('in_person', 'In-person approach'), ('mail', 'Mail'), ('other', 'Other channel')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='scam',
            name='phishing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scam',
            name='scam_type',
            field=models.CharField(choices=[('financial', 'Financial transfer scams'), ('identity', 'Identity and impersonation scams'), ('investment', 'Investment and wealth scams'), ('other', 'Other scams')], max_length=100),
        ),
    ]
