# Generated by Django 4.1 on 2026-04-12 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scams', '0003_scam_contact_method_scam_phishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scam',
            name='amount_lost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scam',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scam',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scam',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('CAD', 'CAD — Canadian Dollar'), ('INR', 'INR — Indian Rupee'), ('NGN', 'NGN — Nigerian Naira'), ('ZAR', 'ZAR — South African Rand'), ('BRL', 'BRL — Brazilian Real'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='scam',
            name='date_occurred',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scam',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scam',
            name='reporter_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='scam',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scam',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scam',
            name='scammer_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scam',
            name='scammer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scam',
            name='severity',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='scam',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone call'), ('sms', 'SMS'), ('email', 'Email'), ('mail', 'Mail'), ('social', 'Social media'), ('messaging', 'Messaging app'), ('website', 'Website / ad'), ('in_person', 'In person approach'), ('other', 'Other channel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='scam',
            name='scam_type',
            field=models.CharField(choices=[('financial', 'Financial transfer scams'), ('identity', 'Identity and impersonation scams'), ('investment', 'Investment and wealth scams'), ('other', 'Other scams')], default='undefined', max_length=100),
        ),
    ]
