# Generated by Django 5.2.13 on 2026-04-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scams', '0004_scam_amount_lost_scam_anonymous_scam_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scam',
            name='date_seen',
        ),
    ]
